[build]
builder = "NIXPACKS"

[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/nixos-23.11.tar.gz"
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "python312Packages.setuptools",
  "python312Packages.wheel",
  "libmysqlclient",        # for mysqlclient binding
  "pkg-config",
  "gcc",
  "gnumake"
]

[phases.setup.environment]
PYTHON_VERSION = "3.12"

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn TransactionApi.wsgi:application --bind 0.0.0.0:$PORT"
