
[build]
builder = "NIXPACKS"

[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/nixos-23.11.tar.gz"


[phases.setup.environment]
PYTHON_VERSION = "3.12"

[phases.setup.nixPackages]
packages = [
  "python312",
  "python312Packages.pip",
  "python312Packages.setuptools",
  "python312Packages.wheel"
]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn TransactionApi.wsgi:application --bind 0.0.0.0:$PORT"
