[phases.setup]
nixPkgs = ["python312", "mysql", "mariadb-connector-c", "pkg-config"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn TransactionApi.wsgi:application --bind 0.0.0.0:$PORT"
