# Generated by Django 5.2.1 on 2025-05-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='owner',
            new_name='account_owner',
        ),
    ]
