# Generated by Django 5.2.1 on 2025-05-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0002_rename_owner_account_account_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
