# Generated by Django 5.2.1 on 2025-05-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_account',
            field=models.ForeignKey(blank=True, help_text='For Send/Receive transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_account', to='transaction_api.account'),
        ),
    ]
