# Generated by Django 5.2.1 on 2025-05-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_api', '0005_transaction_description_transaction_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='processed',
        ),
    ]
